### ISSUE TITLE
NameError: name 'QtWebKitWidgets' is not defined ---- in viewer.py 

### ISSUE THREAD

**Issue by zoldaten** [strayge/rutracker_parser#5]
QtWebKitWidgets is deprecated as to https://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5
So to get it working change in it:
**from PyQt5 import QtWebKitWidgets**
to 
**from PyQt5.QtWebEngineWidgets import QWebEngineView as QWebView,QWebEnginePage as QWebPage**
and 
**self.webview = QtWebKitWidgets.QWebView**
to
**self.webview = QWebView()**

Thats it.

**Comment by strayge** [comment]
In current state project completely outdated.

Not sure minor patches has any sense.

**Comment by strayge** [comment]
made minor updates in master

now it works (tested on small set of pages).
